spring:
  datasource:
    url: jdbc:postgresql://${USERS_DB_HOST}:${USERS_DB_PORT}/${USERS_DB_NAME}
    username: ${USERS_DB_USER}
    password: ${USERS_DB_PASS}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com.lendora.audit: DEBUG