spring:
  application:
    name: lendora-users
  datasource:
    url: jdbc:postgresql://${DEV_DB_HOST:pg}:${DEV_DB_PORT:5432}/${DEV_DB_NAME:lendora_dev}
    username: ${DEV_DB_USER:lendora}
    password: ${DEV_DB_PASS:lendora}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update           # para DEV; en prod usa 'validate' + Flyway
    properties:
      "[hibernate.jdbc.time_zone]": UTC
      "[hibernate.format_sql]": true
      "[hibernate.default_schema]": public
server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

lendora:
  security:
    jwt:
      secret: ${APP_JWT_SECRET_B64:Q72RopRX1br84N16I7O/7uWmCjSxjWAW+G03c0NDtEQ=}
      expiration-ms: ${APP_JWT_EXPIRATION_MS:900000}
    login:
      threshold: ${APP_LOGIN_THRESHOLD:5}
      window:
        minutes: ${APP_LOGIN_WINDOW_MINUTES:15}
      lock:
        minutes: ${APP_LOGIN_LOCK_MINUTES:15}
  services:
    auth:
      internal:
        secret: ${INTERNAL_AUTH_SECRET:Q72RopRX1br84N16I7O/7uWmCjSxjWAW+G03c0NDtEQ=}
      