spring:
  config:
    import: optional:configtree:/run/secrets/
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${USERS_DB_NAME}
    username: ${USERS_DB_USER}
    password: ${users_db_pass}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate