spring:
  application:
    name: lendora-users

  datasource:
    url: jdbc:postgresql://${USERS_DB_HOST}:${USERS_DB_PORT}/${USERS_DB_NAME}
    username: ${USERS_DB_USER}
    password: ${USERS_DB_PASS}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update      # DEV: update; PROD: validate + Flyway
    properties:
      "[hibernate.jdbc.time_zone]": UTC
      "[hibernate.format_sql]": true
      "[hibernate.default_schema]": public
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_JWKS_URI}

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
lendora:
  services:
    auth:
      internal:
        secret: ${INTERNAL_AUTH_SECRET}
  security:
    login:
      threshold: ${APP_LOGIN_THRESHOLD:5}
      window:
        minutes: ${APP_LOGIN_WINDOW_MINUTES:15}
      lock:
        minutes: ${APP_LOGIN_LOCK_MINUTES:15}